// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgbO9BmPzpb9Hp4IHa7u4RJ0lb3E5d28s',
    appId: '1:343628565402:web:50ee73e8c3d762027b4823',
    messagingSenderId: '343628565402',
    projectId: 'cheddar-a1c3a',
    authDomain: 'cheddar-a1c3a.firebaseapp.com',
    storageBucket: 'cheddar-a1c3a.firebasestorage.app',
    measurementId: 'G-5DHMS73BC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZGOUiHe00o7_mbB8mnWViHt8uiXc75Og',
    appId: '1:343628565402:android:8cb6bf6209b949c37b4823',
    messagingSenderId: '343628565402',
    projectId: 'cheddar-a1c3a',
    storageBucket: 'cheddar-a1c3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoeQRQEFVQQ3JtnhbO_wptX3W2_83PJZk',
    appId: '1:343628565402:ios:fb2bedb04de166597b4823',
    messagingSenderId: '343628565402',
    projectId: 'cheddar-a1c3a',
    storageBucket: 'cheddar-a1c3a.firebasestorage.app',
    androidClientId: '343628565402-5nnasvgib8v8a2g3mf35upprdji7n16u.apps.googleusercontent.com',
    iosClientId: '343628565402-to8smdibnob8gms8kfemh7nf8rrn4qc2.apps.googleusercontent.com',
    iosBundleId: 'com.example.cheddar',
  );
}
